### PR TITLE
Add Fyne to the list of Linux ready toolkits :)

### PR DESCRIPTION
**Pull request by andydotxyz**
Fyne is a great option for developers looking to the Go language for development.
And there is FyneDesk which is a full Linux desktop, as well as Fin for display management.

### CODE REVIEW

**Review by Jacalz — APPROVED** [review]
Looks good to me :)

**Comment by andydotxyz** [comment]
Is there anything additional required to consider merging this @popey ?

**Comment by andydotxyz** [comment]
Is anyone able to approve or is the project dormant?

**Comment by probonopd** [comment]
Well I guess if not even Qt is approved, then at least it has nothing to do with Fyne ;-)

* https://github.com/popey/makealinux.app/pull/17

**Comment by popey** [comment]
Thanks for the pull request. Sorry, it's taken a while to get back to this. 
I've decided to reboot this initiative and move the repo to a new location while we work on it. 

I hope you'll join us there. 

https://github.com/makealinuxapp/makealinuxapp

**Pull request closed without merging**
